import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { useEffect, useState } from "react";
import Avatar from "@mui/material/Avatar";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import FacebookIcon from "@mui/icons-material/Facebook";
import TwitterIcon from "@mui/icons-material/Twitter";
import LanguageIcon from "@mui/icons-material/Language";

import VerifiedIcon from "@mui/icons-material/Verified";
import Navbar from "../../components/layout/Navbar";
import Accreditation from "../../components/provider/Accreditation";

export default function Organization({ provider, programmes }) {
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading] = useState(null);
  const [credentials, setCredentials] = useState(null);
  const [programmesdata, setProgrammesdata] = useState(null);

  useEffect(() => {
    loadAnalytics();
  }, []);
  async function loadAnalytics() {
    setLoading(true);
    const res = await axios.get(`/api/providers/stats/${provider._id}`);
    setAnalytics(res.data);
    setCredentials(res.data.credentials[0]?.total_credentials);
    setProgrammesdata(res.data.totalProgrammes[0]?.total_programmes);
    setLoading(false);
  }
  return (
    <div>
      <Head>
        <title>{provider.institution_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container maxWidth="lg">
        <Box sx={{ mt: 3 }}>
          <Box sx={{ m: 1 }}>
            <Box sx={{ display: "flex", m: 2 }}>
              {provider.profile_img ? (
                <img src={provider.profile_img} style={{ width: 150 }} />
              ) : (
                <Avatar variant="rounded" sx={{ width: 110, height: 110 }} />
              )}
            </Box>
            <Typography variant="h4" sx={{ m: 1 }}>
              {provider.institution_name}
            </Typography>
            <Typography variant="body1" sx={{ m: 1 }}>
              {provider.headline}
            </Typography>
            <Box sx={{ m: 1 }}>
              {provider.links?.linkedIn ? (
                <Link href={provider.links.linkedIn} passHref={true}>
                  <LinkedInIcon color="primary" sx={{ mr: 1 }} />
                </Link>
              ) : null}
              {provider.links?.facebook ? (
                <Link href={provider.links.facebook} passHref={true}>
                  <FacebookIcon color="primary" sx={{ mr: 1 }} />
                </Link>
              ) : null}
              {provider.links?.twitter ? (
                <Link href={provider.links.twitter} passHref={true}>
                  <TwitterIcon color="primary" sx={{ mr: 1 }} />
                </Link>
              ) : null}
              {provider.links?.webUrl ? (
                <Link href={provider.links.webUrl} passHref={true}>
                  <LanguageIcon color="primary" sx={{ mr: 1 }} />
                </Link>
              ) : null}
            </Box>
            <Box sx={{ display: "flex", m: 1 }}>
              {programmesdata && (
                <Typography
                  variant="subtitle1"
                  color="text.secondary"
                  sx={{ mr: 2 }}
                >
                  {programmesdata} programmes
                </Typography>
              )}
              {credentials && (
                <Typography
                  variant="subtitle1"
                  color="text.secondary"
                  sx={{ mr: 2 }}
                >
                  {credentials} credentials issued
                </Typography>
              )}
            </Box>
          </Box>
          {provider.is_accredited ? (
            <Box sx={{ display: "flex", ml: 1 }}>
              <VerifiedIcon sx={{ color: "#26c6da", m: 1 }} />

              <Typography variant="body1" sx={{ m: 1, ml: 0 }}>
                Is accredited
              </Typography>
            </Box>
          ) : null}
          <Paper sx={{ backgroundColor: "#eeeeee", m: 2, p: 2 }}>
            <Typography variant="h5" sx={{ m: 2 }}>
              About
            </Typography>
            <Box sx={{ textAlign: "justify" }}>
              <Typography variant="body1" sx={{ m: 2 }}>
                {provider.description}
              </Typography>
            </Box>
          </Paper>
        </Box>
        <Box sx={{ mt: 4, ml: 1, mb: 4 }}>
          <Accreditation documents={provider.documents} />
        </Box>
      </Container>
    </div>
  );
}

export const getServerSideProps = async ({ params }) => {
  const res = await axios.get(
    `https://vyeti.vercel.app/api/providers/org/${params.slug}`
  );
  return {
    props: {
      provider: res.data.provider,
      programmes: res.data.programmes,
    },
  };
};
