import Head from "next/head";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import InsightsIcon from "@mui/icons-material/Insights";
import VerifiedOutlinedIcon from "@mui/icons-material/VerifiedOutlined";
import CardMembershipIcon from "@mui/icons-material/CardMembership";
import AccountCircleOutlinedIcon from "@mui/icons-material/AccountCircleOutlined";
import Navbar from "../components/layout/Navbar";
import Grid from "@mui/material/Grid";

export default function Home() {
  const talkingpoints = [
    "Issue Digital Certificates",
    "Verify Individuals Credentials",
    "Broadcast Your Skills",
    "Gain Insightful Data",
  ];
  return (
    <div>
      <Head>
        <title>Vyeti </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Grid container spacing={2}>
        <Grid item xs={6}>
          <Box sx={{ ml: 12, mr: 6, mt: 3 }}>
            <Typography
              variant="h2"
              component="h1"
              color="primary"
              sx={{ fontFamily: "sans" }}
            >
              Verifiable Blockchain Credentials.
            </Typography>
            <Typography variant="h6" sx={{ mt: 2 }}></Typography>
            {talkingpoints.map((points, index) => (
              <Box
                sx={{
                  backgroundColor: "#e3f2fd",
                  borderRadius: 2,
                  p: 1.2,
                  mt: 2,
                  display: "flex",
                }}
                key={index}
              >
                {index === 0 ? (
                  <CardMembershipIcon sx={{ m: 2, mr: 0 }} />
                ) : index === 1 ? (
                  <VerifiedOutlinedIcon sx={{ m: 2, mr: 0 }} />
                ) : index === 2 ? (
                  <AccountCircleOutlinedIcon sx={{ m: 2, mr: 0 }} />
                ) : (
                  <InsightsIcon sx={{ m: 2, mr: 0 }} />
                )}
                <Typography
                  variant="h6"
                  sx={{ m: 1, ml: 3, fontFamily: "sans" }}
                >
                  {points}
                </Typography>
              </Box>
            ))}
          </Box>
        </Grid>
        <Grid item xs={6}>
          <Box sx={{ mt: -8, maxWidth: 100, ml: -4 }}>
            <img src="certificate.png" style={{ maxWidth: "700px" }} />
          </Box>
        </Grid>
        <Box sx={{ m: 5 }} />
      </Grid>
    </div>
  );
}
